const presentationPresets = {
  default: {
    template: 'editorial',
    layout: 'editorial',
    branding: {
      wordmark: 'SABORE',
      subtitle: 'COCINA DE AUTOR',
    },
    theme: {
      id: 'ivory-olive',
      background: '#f4efe6',
      surface: '#fffdfa',
      surfaceAlt: '#f8f4ec',
      text: '#1b1b18',
      muted: 'rgba(27, 27, 24, 0.72)',
      primary: '#445d39',
      primaryText: '#fffdf8',
      accent: '#4f6546',
      border: 'rgba(96, 91, 74, 0.12)',
      shadow: 'rgba(45, 38, 24, 0.08)',
      displayFont: 'Cormorant Garamond',
      bodyFont: 'Manrope',
    },
    hero: {
      image: '/dishes/hero-clean-cut.png',
      title: 'Buen sabor,',
      accent: 'buen momento',
      description: 'Descubre nuestra seleccion de platos hechos para ti.',
    },
    cards: {
      style: 'editorial-list',
    },
    preview: {
      productMedia: 'video-first',
      autoplayVideos: true,
      mutedVideos: true,
    },
  },
  bistro: {
    template: 'bistro',
    layout: 'bistro',
    branding: {
      wordmark: 'BRUDER',
      subtitle: 'KITCHEN HOUSE',
    },
    theme: {
      id: 'charcoal-spritz',
      background: '#f5efe8',
      surface: '#fff9f3',
      surfaceAlt: '#f3eadf',
      text: '#241d17',
      muted: 'rgba(36, 29, 23, 0.68)',
      primary: '#8c4b2f',
      primaryText: '#fff9f3',
      accent: '#41583f',
      border: 'rgba(140, 75, 47, 0.14)',
      shadow: 'rgba(68, 43, 28, 0.1)',
      displayFont: 'Fraunces',
      bodyFont: 'DM Sans',
    },
    hero: {
      image: '/dishes/hero-clean-cut.png',
      title: 'Cocina honesta,',
      accent: 'mesa vibrante',
      description: 'Sabores directos, visual fuerte y una carta hecha para convertir.',
    },
    cards: {
      style: 'magazine-list',
    },
    preview: {
      productMedia: 'video-first',
      autoplayVideos: true,
      mutedVideos: true,
    },
  },
  luxe: {
    template: 'luxe',
    layout: 'luxe',
    branding: {
      wordmark: "SANDRA'S",
      subtitle: 'DINING EXPERIENCE',
    },
    theme: {
      id: 'night-gold',
      background: '#161311',
      surface: '#221c18',
      surfaceAlt: '#1b1613',
      text: '#f7f0e4',
      muted: 'rgba(247, 240, 228, 0.72)',
      primary: '#b88c54',
      primaryText: '#1a1410',
      accent: '#d3b17a',
      border: 'rgba(211, 177, 122, 0.18)',
      shadow: 'rgba(0, 0, 0, 0.24)',
      displayFont: 'Playfair Display',
      bodyFont: 'Manrope',
    },
    hero: {
      image: '/dishes/hero-steak.jpg',
      title: 'Una carta',
      accent: 'con atmosfera',
      description: 'Experiencia nocturna, tipografia elegante y foco total en el producto.',
    },
    cards: {
      style: 'glass-list',
    },
    preview: {
      productMedia: 'video-first',
      autoplayVideos: true,
      mutedVideos: true,
    },
  },
  gelato: {
    template: 'gelato',
    layout: 'gelato',
    branding: {
      wordmark: 'Dolce',
      subtitle: 'HELADERIA',
    },
    theme: {
      id: 'gelato-candy',
      background: '#fff8fb',
      surface: '#ffffff',
      surfaceAlt: '#fff6fa',
      text: '#22183b',
      muted: 'rgba(34, 24, 59, 0.68)',
      primary: '#ff5a92',
      primaryText: '#fffafc',
      accent: '#b96ed8',
      border: 'rgba(255, 113, 166, 0.12)',
      shadow: 'rgba(226, 102, 149, 0.12)',
      displayFont: 'Baloo 2',
      bodyFont: 'Manrope',
    },
    hero: {
      image: '/dishes/hero-clean-cut.png',
      title: 'Hola!',
      accent: 'Que se te antoja hoy?',
      description: 'Elegi formato, tamano y sabores en pocos pasos.',
    },
    cards: {
      style: 'gelato-cards',
    },
    preview: {
      productMedia: 'video-first',
      autoplayVideos: true,
      mutedVideos: true,
    },
  },
  pizzeria: {
    template: 'pizzeria',
    layout: 'pizzeria',
    branding: {
      wordmark: 'LA BUONA',
      subtitle: 'PIZZERIA',
    },
    theme: {
      id: 'pizzeria-olive',
      background: '#f5f0e6',
      surface: '#fffaf1',
      surfaceAlt: '#faf2e4',
      text: '#2c2c2c',
      muted: 'rgba(44, 44, 44, 0.82)',
      primary: '#17361f',
      primaryText: '#fffaf1',
      accent: '#2d5a31',
      border: 'rgba(23, 54, 31, 0.1)',
      shadow: 'rgba(16, 28, 16, 0.12)',
      displayFont: 'Cinzel',
      bodyFont: 'Montserrat',
    },
    hero: {
      title: 'NUESTRO MENÚ',
      image: '/pizzeria/header.png',
      accent: 'Sabor que te hace volver',
      description: 'Pizza, entradas, bebidas y postres.',
    },
    cards: {
      style: 'pizzeria-grid',
    },
    preview: {
      productMedia: 'video-first',
      autoplayVideos: true,
      mutedVideos: true,
    },
  },
  burger: {
    template: 'burger',
    layout: 'burger',
    branding: {
      wordmark: 'BRASA',
      subtitle: 'BURGER CO.',
    },
    theme: {
      id: 'brasa-burger',
      background: '#080c0d',
      surface: '#111719',
      surfaceAlt: '#0b1011',
      text: '#f8f3e8',
      muted: 'rgba(248, 243, 232, 0.72)',
      primary: '#f5b72e',
      primaryText: '#100f0c',
      accent: '#ff8b21',
      border: 'rgba(255, 255, 255, 0.16)',
      shadow: 'rgba(0, 0, 0, 0.35)',
      displayFont: 'Bebas Neue',
      bodyFont: 'Montserrat',
    },
    hero: {
      image: '/burger/header.png',
      title: 'SABOR',
      accent: 'QUE SE RECUERDA',
      description: 'Carne premium. Ingredientes reales. Hechas al fuego.',
    },
    cards: {
      style: 'burger-grid',
    },
    preview: {
      productMedia: 'video-first',
      autoplayVideos: true,
      mutedVideos: true,
    },
  },
  blueBurger: {
    template: 'blue-burger',
    layout: 'blue-burger',
    branding: {
      wordmark: 'JBurger',
      subtitle: 'BURGER HOUSE',
    },
    theme: {
      id: 'blue-burger',
      background: '#f6efe5',
      surface: '#fffdf8',
      surfaceAlt: '#f2e8da',
      text: '#16304a',
      muted: '#29445e',
      primary: '#0f5182',
      primaryText: '#fffdf8',
      accent: '#1c64a0',
      border: 'rgba(15, 81, 130, 0.12)',
      shadow: 'rgba(22, 48, 74, 0.12)',
      displayFont: 'Bebas Neue',
      bodyFont: 'Montserrat',
    },
    hero: {
      image: '/dishes/hero-steak.jpg',
      title: 'HAMBURGUESAS',
      accent: 'DE VERDAD',
      description: 'Ingredientes frescos, carne de calidad y todo el sabor.',
    },
    cards: {
      style: 'blue-burger-list',
    },
    preview: {
      productMedia: 'video-first',
      autoplayVideos: true,
      mutedVideos: true,
    },
  },
  host: {
    template: 'host',
    layout: 'host',
    branding: {
      wordmark: 'HOST',
      subtitle: 'CRISPY HOUSE',
    },
    theme: {
      id: 'host-crispy',
      background: '#000000',
      pageBackground: '#000000',
      contentBackground: '#000000',
      surface: '#0a0f10',
      surfaceAlt: '#0b0b0d',
      text: '#fff6ea',
      muted: 'rgba(255, 246, 234, 0.72)',
      primary: '#ffbe31',
      primaryText: '#150d08',
      accent: '#ef3b2d',
      categoryActiveBackground: '#ffbe31',
      categoryActiveText: '#150d08',
      categoryText: '#fff6ea',
      cardBackground: '#0a0f10',
      cardText: '#fff6ea',
      cardPrice: '#ffbe31',
      addButtonBackground: '#ffbe31',
      addButtonText: '#150d08',
      border: 'rgba(255, 255, 255, 0.12)',
      shadow: 'rgba(0, 0, 0, 0.34)',
      displayFont: 'Bebas Neue',
      bodyFont: 'Montserrat',
    },
    hero: {
      title: 'EL CRYSPY',
      accent: 'NUNCA MIENTE!',
      description: 'Pollo frito crujiente, sabroso y recien hecho para vos.',
    },
    cards: {
      style: 'host-grid',
    },
    preview: {
      productMedia: 'video-first',
      autoplayVideos: true,
      mutedVideos: true,
    },
  },
  kika: {
    template: 'kika',
    layout: 'kika',
    branding: {
      wordmark: 'KIKA',
      subtitle: 'CAFE',
    },
    theme: {
      id: 'kika-cafe',
      background: '#f5efe6',
      pageBackground: '#f5efe6',
      contentBackground: '#fffaf3',
      surface: '#fffaf3',
      surfaceAlt: '#f1e7da',
      text: '#263420',
      muted: 'rgba(38, 52, 32, 0.7)',
      primary: '#557348',
      primaryText: '#fffaf3',
      accent: '#5f7755',
      border: 'rgba(88, 105, 70, 0.18)',
      shadow: 'rgba(60, 46, 28, 0.13)',
      displayFont: 'Cormorant Garamond',
      bodyFont: 'Manrope',
      categoryActiveBackground: '#557348',
      categoryActiveText: '#fffaf3',
      cardBackground: '#fffdf8',
      cardText: '#263420',
      cardMuted: 'rgba(38, 52, 32, 0.66)',
      cardPrice: '#557348',
      addButtonBackground: '#557348',
      addButtonText: '#fffaf3',
    },
    hero: {
      image: '/kika/header.png',
      title: 'Tu nuevo',
      accent: 'lugar favorito',
      description: 'Cafe, pasteleria y buenos momentos.',
    },
    cards: {
      style: 'kika-cards',
    },
    preview: {
      productMedia: 'video-first',
      autoplayVideos: true,
      mutedVideos: true,
    },
  },
  almendra: {
    template: 'almendra',
    layout: 'almendra',
    branding: {
      wordmark: 'ALMENDRA',
      subtitle: 'CAFE DE ESPECIALIDAD',
    },
    theme: {
      id: 'almendra-cafe',
      background: '#f5ede4',
      pageBackground: '#f5ede4',
      contentBackground: '#fbf4ed',
      surface: '#fff9f3',
      surfaceAlt: '#f0e2d5',
      text: '#4b2d1d',
      muted: 'rgba(75, 45, 29, 0.68)',
      primary: '#5b3219',
      primaryText: '#fff8f0',
      accent: '#8a5a3c',
      border: 'rgba(91, 50, 25, 0.18)',
      shadow: 'rgba(80, 45, 22, 0.12)',
      displayFont: 'Cormorant Garamond',
      bodyFont: 'Manrope',
      categoryActiveBackground: '#5b3219',
      categoryActiveText: '#fff8f0',
      categoryText: '#4b2d1d',
      cardBackground: 'transparent',
      cardText: '#4b2d1d',
      cardMuted: 'rgba(75, 45, 29, 0.68)',
      cardPrice: '#4b2d1d',
      addButtonBackground: '#fff9f3',
      addButtonText: '#5b3219',
    },
    hero: {
      image: '/almendra/header.png',
      video: '',
      title: 'DISFRUTÁ',
      accent: 'LO SIMPLE,',
      description: 'LO ESENCIAL.',
    },
    cards: {
      style: 'almendra-list',
    },
    preview: {
      productMedia: 'video-first',
      autoplayVideos: true,
      mutedVideos: true,
    },
  },
  florian: {
    template: 'florian',
    layout: 'florian',
    branding: {
      wordmark: 'FLORIAN',
      subtitle: 'CAFE DE ESPECIALIDAD',
    },
    theme: {
      id: 'florian-cafe',
      background: '#f5eee5',
      pageBackground: '#f5eee5',
      contentBackground: '#f7efe7',
      surface: '#fff8f1',
      surfaceAlt: '#efe2d5',
      text: '#172a34',
      muted: 'rgba(23, 42, 52, 0.72)',
      primary: '#c64b32',
      primaryText: '#fff8f1',
      accent: '#d36345',
      border: 'rgba(198, 75, 50, 0.2)',
      shadow: 'rgba(57, 43, 30, 0.13)',
      displayFont: 'Bebas Neue',
      bodyFont: 'Montserrat',
      categoryActiveBackground: '#fff8f1',
      categoryActiveText: '#c64b32',
      categoryText: '#172a34',
      cardBackground: 'transparent',
      cardText: '#172a34',
      cardMuted: 'rgba(23, 42, 52, 0.68)',
      cardPrice: '#c64b32',
      addButtonBackground: '#c64b32',
      addButtonText: '#fff8f1',
    },
    hero: {
      video: '',
      title: 'BUEN CAFE,',
      accent: 'BUENOS MOMENTOS.',
      description: 'Cafe de especialidad y cocina simple, hecha con pasion en Chivilcoy.',
    },
    cards: {
      style: 'florian-list',
    },
    preview: {
      productMedia: 'video-first',
      autoplayVideos: true,
      mutedVideos: true,
    },
  },
  saborPampa: {
    template: 'sabor-pampa',
    layout: 'sabor-pampa',
    branding: {
      wordmark: 'sabor a pampa',
      subtitle: 'cocina casera',
    },
    theme: {
      id: 'sabor-pampa',
      background: '#030505',
      pageBackground: '#030505',
      contentBackground: '#050706',
      surface: '#11100d',
      surfaceAlt: '#0a0b09',
      text: '#f7efe2',
      muted: 'rgba(247, 239, 226, 0.74)',
      primary: '#f4b739',
      primaryText: '#090806',
      accent: '#e0a329',
      border: 'rgba(244, 183, 57, 0.22)',
      shadow: 'rgba(0, 0, 0, 0.42)',
      displayFont: 'Fraunces',
      bodyFont: 'Montserrat',
      categoryActiveBackground: '#f4b739',
      categoryActiveText: '#090806',
      categoryText: '#f7efe2',
      cardBackground: '#10100d',
      cardText: '#f7efe2',
      cardMuted: 'rgba(247, 239, 226, 0.72)',
      cardPrice: '#f4b739',
      addButtonBackground: '#f4b739',
      addButtonText: '#090806',
    },
    hero: {
      image: '',
      video: '',
      title: 'CASERO, GOURMET',
      accent: 'y hecho con amor',
      description: 'Platos que reconfortan, sabores que te hacen volver.',
    },
    cards: {
      style: 'sabor-pampa-cards',
    },
    preview: {
      productMedia: 'video-first',
      autoplayVideos: true,
      mutedVideos: true,
    },
  },
}

const accountPresentations = {
  editorial: presentationPresets.default,
  default: presentationPresets.default,
  bistro: presentationPresets.bistro,
  luxe: presentationPresets.luxe,
  gelato: presentationPresets.gelato,
  pizzeria: presentationPresets.pizzeria,
  totta: presentationPresets.default,
  'sandras-rose': presentationPresets.luxe,
  bruder: presentationPresets.bistro,
  heladeria: presentationPresets.gelato,
  'la-esquina': presentationPresets.pizzeria,
  laesquina: presentationPresets.pizzeria,
  laesquinacba: presentationPresets.pizzeria,
  burguer: presentationPresets.burger,
  burger: presentationPresets.burger,
  brasa: presentationPresets.burger,
  'el-club': presentationPresets.burger,
  'blue-burger': presentationPresets.blueBurger,
  jburger: presentationPresets.blueBurger,
  host: presentationPresets.host,
  kika: presentationPresets.kika,
  almendra: presentationPresets.almendra,
  florian: presentationPresets.florian,
  'sabor-a-pampa': presentationPresets.saborPampa,
  saborapampa: presentationPresets.saborPampa,
  'sabor-pampa': presentationPresets.saborPampa,
  'sabor-a-pampa-cocina': presentationPresets.saborPampa,
  'capta-demo': presentationPresets.default,
}

export function resolveMenuPresentation(accountId) {
  return accountPresentations[accountId] ?? presentationPresets.default
}
